### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by alfuken** [unascribed/Laminate#1]
Subj

**Comment by exaskye** [comment]
No, just dormant due to lack of need. All the base stuff is in place, but it needs to get updated to 1.11.2 and have the rest of the components implemented.

**Comment by alfuken** [comment]
It's just it seems like your project is the only decent GUI lib for 1.7.10, and one is deprecated and another is "dormant". Sad. :/

**Comment by exaskye** [comment]
There's been a lot of discussion about the project lately, and I'm likely to pick it up again soon. See: #2, #3. I'm just in the middle of another project at the moment.

GUIs have changed little (if at all) in recent versions, so 1.7.x support will be maintained when I get back onto the project.

**Comment by alfuken** [comment]
Cool! Thanks for the update. :)

**Comment by alfuken** [comment]
*sigh*... Nothing changed :(

**Comment by alfuken** [comment]
This thing really lacks a text field, button and scroll panel... With this it'd be workable.

**Comment by LemmaEOF** [comment]
I'd say this project is pretty much dead at this point. Una's taking a break from Minecraft modding and the elytra team already has a very strong gui framework within [Concrete](https://github.com/elytra/Concrete). I'd recommend you check that out instead.

**Comment by exaskye** [comment]
Note that Concrete's GUI framework is for inventories, which is not the same purpose as Laminate.

-------- Original Message --------

**Comment by exaskye** [comment]
Sorry for never having gotten back to this, I stayed unexpectedly busy with work and once I did get some time off last week I just didn't want to mod Minecraft anymore.

-------- Original Message --------
